# Generated by Django 2.2.24 on 2023-09-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, choices=[(True, 'новостройка'), (False, 'старое здание'), (None, 'не заполнено')], default=None, null=True, verbose_name='Здание'),
        ),
    ]
