# Generated by Django 2.2.24 on 2023-09-29 11:59

from django.db import migrations


def change_new_building(apps, schema_editor):
    year = 2015
    Flat = apps.get_model('property', 'Flat')
    built_later_flat = Flat.objects.filter(construction_year__gte=year)
    built_earlier_flat = Flat.objects.filter(construction_year__lt=year)
    built_later_flat.update(new_building=True)
    built_earlier_flat.update(new_building=False)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20230929_1414'),
    ]

    operations = [
        migrations.RunPython(change_new_building),
    ]
