# Generated by Django 2.2.24 on 2023-09-29 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0006_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='like',
            field=models.ManyToManyField(related_name='like_flats', to=settings.AUTH_USER_MODEL, verbose_name='Кто лайкнул'),
        ),
    ]
