# Generated by Django 3.2.21 on 2023-10-05 13:23

from django.db import migrations


def link_owners_and_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    flats = Flat.objects.all()

    for flat_obj in flats.iterator():
        obj_owner, created = Owner.objects.get_or_create(owner=flat_obj.owner,
                                                         owners_phonenumber=flat_obj.owners_phonenumber,
                                                         owner_pure_phone=flat_obj.owners_phonenumber,
                                                         )
        obj_owner.owner_apartments.set([flat_obj])


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    Owner.owner_apartments.through.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20230930_1527'),
    ]

    operations = [
        migrations.RunPython(link_owners_and_flats, move_backward)
    ]
