# Generated by Django 3.2.21 on 2023-10-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20231005_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Flat',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='Flat',
            name='owners_phonenumber',
        )
    ]
