# Generated by Django 3.2.21 on 2023-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_auto_20231005_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Наличие балкона'),
        ),
    ]
